// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIVRckh4YK_epEr-IZODTiiMz2nkSzr2U',
    appId: '1:288730985225:web:36d9fbca96c5f3e6c699d8',
    messagingSenderId: '288730985225',
    projectId: 'hospital-b5914',
    authDomain: 'hospital-b5914.firebaseapp.com',
    storageBucket: 'hospital-b5914.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX77ibdcpEsb16QWSGl9MpWNjwyYR0zMM',
    appId: '1:288730985225:android:603cb06a5f3e8564c699d8',
    messagingSenderId: '288730985225',
    projectId: 'hospital-b5914',
    storageBucket: 'hospital-b5914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8fRpXGjL2fPKDeUugJokqZdz6_TOIciQ',
    appId: '1:288730985225:ios:9d48718ecc5f4dadc699d8',
    messagingSenderId: '288730985225',
    projectId: 'hospital-b5914',
    storageBucket: 'hospital-b5914.appspot.com',
    iosBundleId: 'com.example.clinicProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8fRpXGjL2fPKDeUugJokqZdz6_TOIciQ',
    appId: '1:288730985225:ios:a67f6a7422434a25c699d8',
    messagingSenderId: '288730985225',
    projectId: 'hospital-b5914',
    storageBucket: 'hospital-b5914.appspot.com',
    iosBundleId: 'com.example.clinicProject.RunnerTests',
  );
}
